baseURL = "https://example.com/"
theme = "salinger"
title = "Home"
copyright = 'N/A'
ignoreErrors = ["error-remote-getjson"]

[params]
DateFormat = "January 2006"

author = "Phong Le"
description = "I'm an IT Analyst based i. I like developing and designing random stuffs."
header = "<strong>Hi, I'm Phong. 👋 </strong>"
keywords = [ "Portfolio", "developer", "coding", "maker"]
showHeaderOnHomepage = false
#googleAnalytics = ""
twemoji = true
text404 = "Since the page you were looking for seems like doesn't exist, we <strong>strongly</strong> suggest you to better investigate the URL and/or go back to the <a href=\"/\">home</a>. </br></br> <iframe src=\"https://giphy.com/embed/aCKMaeduKfFXG\" width=\"480\" height=\"480\" frameBorder=\"0\" class=\"giphy-embed\" allowFullScreen></iframe>"
#fontawesomekitcode = ""


[permalinks]
  '/' = '/:slug/'
  'projects' = '/:slug/'

[[params.social]]
name = "github"
url = "https://github.com/Vanphongle"
icon = "fa fa-github"
before = "Reach me on "

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/van-p-le/"
icon = "fa fa-linkedin"
before = "and "

[[params.social]]
name = "email"
icon = "fa fa-envelope"
url = "vanp.le@outlook.com"
before = ", or drop me a line on"
after = "."




[Menu]
[[Menu.Main]]
name = "Projects."
url = "/projects/"
weight = 1

[[Menu.Main]]
name = "Contact me."
url = "/contact/"
weight = 2

[taxonomies]
	tag = "tags"
	category = "categories"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true