name: Deploy Hugo Site

on:
  push:
    branches:
      - main # Replace with your default branch name, if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build
      run: hugo --minify

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: your-aws-region
        role-to-assume: arn:aws:iam::123456789012:role/GitHubActionsRole
        role-duration-seconds: 1200
        role-session-name: GitHubActions
        web-identity-token-file: ${{ steps.github-metadata.outputs.token_path }}

    - name: Deploy to S3
      run: aws s3 sync public/ s3://your-bucket-name/ --acl public-read --follow-symlinks --delete
